version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=dpg-d07rmc24d50c73ff3f00-a;Port=5432;Database=formsappdb2;Username=formsappdb2_user;Password=x8SkaRKGRFDtUNuLzH5crv4d1TyfAIJa;SSL Mode=Require;Trust Server Certificate=true"
    restart: always